# version: 2.1

# jobs:
#    build:
#     docker:
#       - image: cimg/node:20.10
#     working_directory: ~/repo

#     steps:
#       - checkout

#       - run:
#           name: Install Dependencies
#           command: npm ci

#       - run:
#           name: Build App
#           command: npm run build

#    deploy:
#     docker:
#       - image: cimg/node:20.10

#     steps:
#       - checkout

#       - add_ssh_keys:
#           fingerprints:
#             - "SHA256:7xjWHGCECl0EB+4XN/zq/zGqnFvr0AVdaCbJta0mlao"

#       - run:
#           name: Deploy to Server
#           command: |
#             ssh -o StrictHostKeyChecking=no $root@$154.12.117.217 << 'EOF'
#               cd /root/test-project

#               git pull origin main
#               npm ci
#               npm run build

#               pm2 restart next-app || pm2 start npm --name "next-app" -- start
#             EOF

# workflows:
#   version: 2
#   build_and_deploy:
#     jobs:
#       - build
#       - deploy:
#           requires:
#             - build
#           filters:
#             branches:
#               only: main



version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:18.18

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "SHA256:mKwcyqjePxsIsylsINA6aTxk7TPRZR9hnmAvo8OjtHY circleci"

      - run:
          name: Deploy to VPS
          command: |
            ssh -o StrictHostKeyChecking=no $root@154.12.117.217 << 'EOF'
              cd /var/www/nextjs-app

              git pull origin main

              npm install

              npm run build

              pkill node || true

              nohup npm start > output.log 2>&1 &
            EOF

workflows:
  deploy:
    jobs:
      - deploy